controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_group_position_controller:
  ros__parameters:
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3

    command_interfaces:
      - position

    state_interfaces:
      - position
